version: '3.3'
services:
  chall:
    build:
      context: ./Docker
    image: dctf_chall:latest
    restart: always
    privileged: true
    entrypoint: /bin/bash
    command: /home/ctf/startup.sh
    ports:
      - "1337:3000"
